export interface HSNEntry {
  code: string;
  description: string;
  gstRate: number;
  chapter: string;
}

// Comprehensive HSN/SAC code database — covers common goods (Chapters 1–96) and services (SAC 99xx)
export const HSN_DATA: HSNEntry[] = [
  // ── Chapter 1–4: Live Animals & Animal Products ──
  { code: '0101', description: 'Live horses, asses, mules and hinnies', gstRate: 0, chapter: 'Live Animals' },
  { code: '0102', description: 'Live bovine animals (cattle, buffalo)', gstRate: 0, chapter: 'Live Animals' },
  { code: '0103', description: 'Live swine (pigs)', gstRate: 0, chapter: 'Live Animals' },
  { code: '0105', description: 'Live poultry (fowls, ducks, geese, turkeys)', gstRate: 0, chapter: 'Live Animals' },
  { code: '0201', description: 'Meat of bovine animals, fresh or chilled', gstRate: 0, chapter: 'Meat & Poultry' },
  { code: '0207', description: 'Meat and edible offal of poultry', gstRate: 0, chapter: 'Meat & Poultry' },
  { code: '0301', description: 'Live fish', gstRate: 0, chapter: 'Fish & Seafood' },
  { code: '0302', description: 'Fish, fresh or chilled', gstRate: 5, chapter: 'Fish & Seafood' },
  { code: '0303', description: 'Fish, frozen', gstRate: 5, chapter: 'Fish & Seafood' },
  { code: '0306', description: 'Crustaceans (prawns, shrimps, crabs, lobsters)', gstRate: 5, chapter: 'Fish & Seafood' },
  { code: '0401', description: 'Milk and cream, not concentrated or sweetened', gstRate: 0, chapter: 'Dairy' },
  { code: '0402', description: 'Milk and cream, concentrated or sweetened', gstRate: 5, chapter: 'Dairy' },
  { code: '0403', description: 'Buttermilk, curd, lassi, cream, yogurt', gstRate: 0, chapter: 'Dairy' },
  { code: '0405', description: 'Butter and other fats and oils derived from milk', gstRate: 12, chapter: 'Dairy' },
  { code: '0406', description: 'Cheese and curd', gstRate: 12, chapter: 'Dairy' },
  { code: '0407', description: 'Birds eggs, in shell, fresh, preserved or cooked', gstRate: 0, chapter: 'Eggs' },
  { code: '0409', description: 'Natural honey', gstRate: 0, chapter: 'Honey' },

  // ── Chapter 7–11: Vegetables, Fruits, Cereals ──
  { code: '0701', description: 'Potatoes, fresh or chilled', gstRate: 0, chapter: 'Vegetables' },
  { code: '0702', description: 'Tomatoes, fresh or chilled', gstRate: 0, chapter: 'Vegetables' },
  { code: '0703', description: 'Onions, shallots, garlic, leeks — fresh or chilled', gstRate: 0, chapter: 'Vegetables' },
  { code: '0713', description: 'Dried leguminous vegetables (dal, lentils, beans)', gstRate: 0, chapter: 'Pulses & Legumes' },
  { code: '0714', description: 'Manioc, sweet potatoes, sago', gstRate: 0, chapter: 'Vegetables' },
  { code: '0801', description: 'Coconuts, Brazil nuts, cashew nuts', gstRate: 5, chapter: 'Nuts & Fruits' },
  { code: '0802', description: 'Other nuts — almonds, hazelnuts, walnuts, pistachios', gstRate: 12, chapter: 'Nuts & Fruits' },
  { code: '0803', description: 'Bananas, including plantains', gstRate: 0, chapter: 'Fresh Fruits' },
  { code: '0804', description: 'Dates, figs, pineapples, avocados, guavas, mangoes', gstRate: 0, chapter: 'Fresh Fruits' },
  { code: '0805', description: 'Citrus fruit — oranges, lemons, limes, grapefruit', gstRate: 0, chapter: 'Fresh Fruits' },
  { code: '0901', description: 'Coffee, whether or not roasted or decaffeinated', gstRate: 5, chapter: 'Coffee & Tea' },
  { code: '0902', description: 'Tea, whether or not flavoured', gstRate: 5, chapter: 'Coffee & Tea' },
  { code: '0904', description: 'Pepper; dried or crushed or ground capsicum/chilli', gstRate: 5, chapter: 'Spices' },
  { code: '0906', description: 'Cinnamon and cinnamon-tree flowers', gstRate: 5, chapter: 'Spices' },
  { code: '0907', description: 'Cloves', gstRate: 5, chapter: 'Spices' },
  { code: '0908', description: 'Nutmeg, mace, cardamoms', gstRate: 5, chapter: 'Spices' },
  { code: '0910', description: 'Ginger, saffron, turmeric, thyme, bay leaves, curry', gstRate: 5, chapter: 'Spices' },
  { code: '1001', description: 'Wheat and meslin', gstRate: 0, chapter: 'Cereals & Grains' },
  { code: '1002', description: 'Rye', gstRate: 0, chapter: 'Cereals & Grains' },
  { code: '1003', description: 'Barley', gstRate: 0, chapter: 'Cereals & Grains' },
  { code: '1006', description: 'Rice', gstRate: 0, chapter: 'Cereals & Grains' },
  { code: '1007', description: 'Grain sorghum (jowar)', gstRate: 0, chapter: 'Cereals & Grains' },
  { code: '1008', description: 'Buckwheat, millet, canary seed', gstRate: 0, chapter: 'Cereals & Grains' },
  { code: '1101', description: 'Wheat or meslin flour (atta, maida)', gstRate: 0, chapter: 'Flour & Milling' },
  { code: '1102', description: 'Cereal flours other than wheat (maize, rice, rye)', gstRate: 0, chapter: 'Flour & Milling' },
  { code: '1107', description: 'Malt, whether or not roasted', gstRate: 0, chapter: 'Flour & Milling' },

  // ── Chapter 15–21: Oils, Sugar, Beverages, Food Prep ──
  { code: '1501', description: 'Pig fat, poultry fat', gstRate: 0, chapter: 'Fats & Oils' },
  { code: '1507', description: 'Soya-bean oil and its fractions', gstRate: 5, chapter: 'Edible Oils' },
  { code: '1508', description: 'Ground-nut oil and its fractions', gstRate: 5, chapter: 'Edible Oils' },
  { code: '1511', description: 'Palm oil and its fractions', gstRate: 5, chapter: 'Edible Oils' },
  { code: '1512', description: 'Sunflower-seed, safflower or cotton-seed oil', gstRate: 5, chapter: 'Edible Oils' },
  { code: '1513', description: 'Coconut oil, palm kernel or babassu oil', gstRate: 5, chapter: 'Edible Oils' },
  { code: '1516', description: 'Animal or vegetable fats and oils, hydrogenated', gstRate: 5, chapter: 'Edible Oils' },
  { code: '1517', description: 'Margarine; edible mixtures of animal/vegetable fats', gstRate: 12, chapter: 'Edible Oils' },
  { code: '1701', description: 'Cane or beet sugar and chemically pure sucrose', gstRate: 5, chapter: 'Sugar' },
  { code: '1702', description: 'Other sugars: lactose, glucose, fructose, maltose', gstRate: 18, chapter: 'Sugar' },
  { code: '1704', description: 'Sugar confectionery (without cocoa)', gstRate: 18, chapter: 'Confectionery' },
  { code: '1801', description: 'Cocoa beans, whole or broken, raw or roasted', gstRate: 5, chapter: 'Cocoa & Chocolate' },
  { code: '1806', description: 'Chocolate and other food preparations containing cocoa', gstRate: 28, chapter: 'Cocoa & Chocolate' },
  { code: '1901', description: 'Malt extract; food preparations of flour, groats, etc.', gstRate: 18, chapter: 'Food Preparations' },
  { code: '1902', description: 'Pasta (macaroni, noodles, spaghetti, vermicelli)', gstRate: 12, chapter: 'Food Preparations' },
  { code: '1904', description: 'Prepared foods from cereals — corn flakes, muesli', gstRate: 18, chapter: 'Food Preparations' },
  { code: '1905', description: 'Bread, pastry, cakes, biscuits, wafers', gstRate: 18, chapter: 'Bakery Products' },
  { code: '2001', description: 'Vegetables, fruits, nuts prepared with vinegar', gstRate: 12, chapter: 'Preserved Foods' },
  { code: '2009', description: 'Fruit juices and vegetable juices', gstRate: 12, chapter: 'Beverages' },
  { code: '2101', description: 'Extracts, essences of coffee, tea or maté', gstRate: 18, chapter: 'Beverages' },
  { code: '2201', description: 'Waters, mineral waters and aerated waters (plain)', gstRate: 0, chapter: 'Beverages' },
  { code: '2202', description: 'Waters with added sugar or sweetened; soft drinks', gstRate: 28, chapter: 'Beverages' },
  { code: '2204', description: 'Wine of fresh grapes including fortified wines', gstRate: 0, chapter: 'Alcoholic Beverages' },
  { code: '2208', description: 'Undenatured ethyl alcohol; spirits, liqueurs', gstRate: 0, chapter: 'Alcoholic Beverages' },
  { code: '2401', description: 'Unmanufactured tobacco; tobacco refuse', gstRate: 28, chapter: 'Tobacco' },
  { code: '2402', description: 'Cigars, cigarillos and cigarettes', gstRate: 28, chapter: 'Tobacco' },

  // ── Chapter 25–27: Minerals & Fuels ──
  { code: '2501', description: 'Salt (including table salt, denatured salt)', gstRate: 0, chapter: 'Minerals' },
  { code: '2502', description: 'Unroasted iron pyrites', gstRate: 5, chapter: 'Minerals' },
  { code: '2505', description: 'Natural sands (silica sand, etc.)', gstRate: 5, chapter: 'Minerals' },
  { code: '2510', description: 'Natural calcium phosphates, phosphatic chalk', gstRate: 5, chapter: 'Minerals' },
  { code: '2515', description: 'Marble, travertine, ecaussine and similar calcareous stone', gstRate: 18, chapter: 'Stone' },
  { code: '2516', description: 'Granite, porphyry, basalt, sandstone — rough or squared', gstRate: 18, chapter: 'Stone' },
  { code: '2517', description: 'Pebbles, gravel, broken/crushed stone (aggregate)', gstRate: 5, chapter: 'Stone' },
  { code: '2523', description: 'Portland cement, aluminous cement, slag cement', gstRate: 28, chapter: 'Building Materials' },
  { code: '2524', description: 'Asbestos (all forms)', gstRate: 18, chapter: 'Minerals' },
  { code: '2526', description: 'Natural steatite (talc), crude or rough', gstRate: 18, chapter: 'Minerals' },
  { code: '2701', description: 'Coal; briquettes, ovoids and similar solid fuels', gstRate: 5, chapter: 'Fuels' },
  { code: '2709', description: 'Petroleum oils and oils from bituminous minerals, crude', gstRate: 0, chapter: 'Petroleum' },
  { code: '2710', description: 'Petroleum oils, not crude; petrol, diesel, aviation fuel', gstRate: 0, chapter: 'Petroleum' },
  { code: '2711', description: 'Petroleum gas; LPG, natural gas, propane, butane', gstRate: 5, chapter: 'Petroleum' },

  // ── Chapter 28–38: Chemicals & Pharma ──
  { code: '2801', description: 'Fluorine, chlorine, bromine and iodine', gstRate: 18, chapter: 'Chemicals' },
  { code: '2804', description: 'Hydrogen, rare gases and other non-metals (oxygen)', gstRate: 12, chapter: 'Chemicals' },
  { code: '2807', description: 'Sulphuric acid; oleum', gstRate: 18, chapter: 'Chemicals' },
  { code: '2814', description: 'Ammonia, anhydrous or in aqueous solution', gstRate: 18, chapter: 'Chemicals' },
  { code: '2836', description: 'Carbonates: sodium carbonate (soda ash), bicarbonates', gstRate: 18, chapter: 'Chemicals' },
  { code: '2901', description: 'Acyclic hydrocarbons', gstRate: 18, chapter: 'Petrochemicals' },
  { code: '2915', description: 'Saturated acyclic monocarboxylic acids (acetic acid)', gstRate: 18, chapter: 'Chemicals' },
  { code: '2922', description: 'Amino-compounds with oxygen function (amino acids)', gstRate: 18, chapter: 'Chemicals' },
  { code: '2933', description: 'Heterocyclic compounds with nitrogen', gstRate: 18, chapter: 'Chemicals' },
  { code: '3001', description: 'Glands and other organs for organo-therapeutic use', gstRate: 5, chapter: 'Pharmaceuticals' },
  { code: '3002', description: 'Human/animal blood; vaccines, toxins, cultures', gstRate: 5, chapter: 'Pharmaceuticals' },
  { code: '3003', description: 'Medicaments (not in measured doses) — bulk pharma', gstRate: 12, chapter: 'Pharmaceuticals' },
  { code: '3004', description: 'Medicaments in measured doses (packed for retail)', gstRate: 12, chapter: 'Pharmaceuticals' },
  { code: '3005', description: 'Wadding, gauze, bandages, dressings (medicated)', gstRate: 12, chapter: 'Medical Supplies' },
  { code: '3006', description: 'Pharmaceutical goods (sterile surgical catgut, blood grouping reagents)', gstRate: 12, chapter: 'Medical Supplies' },
  { code: '3101', description: 'Animal or vegetable fertilisers', gstRate: 5, chapter: 'Fertilisers' },
  { code: '3102', description: 'Mineral or chemical nitrogenous fertilisers (urea)', gstRate: 5, chapter: 'Fertilisers' },
  { code: '3105', description: 'Mineral or chemical fertilisers with two/three nutrients', gstRate: 5, chapter: 'Fertilisers' },
  { code: '3201', description: 'Tanning extracts of vegetable origin', gstRate: 18, chapter: 'Dyes & Tanning' },
  { code: '3204', description: 'Synthetic organic colouring matter; dyes and pigments', gstRate: 18, chapter: 'Dyes & Tanning' },
  { code: '3208', description: 'Paints and varnishes (polymers dissolved in non-aqueous medium)', gstRate: 18, chapter: 'Paints & Coatings' },
  { code: '3209', description: 'Paints and varnishes based on acrylic/vinyl polymers', gstRate: 18, chapter: 'Paints & Coatings' },
  { code: '3210', description: 'Other paints and varnishes; prepared water pigments', gstRate: 18, chapter: 'Paints & Coatings' },
  { code: '3301', description: 'Essential oils, resinoids; extracted oleoresins', gstRate: 18, chapter: 'Perfumes & Cosmetics' },
  { code: '3303', description: 'Perfumes and toilet waters', gstRate: 18, chapter: 'Perfumes & Cosmetics' },
  { code: '3304', description: 'Beauty/make-up preparations; skin-care preparations', gstRate: 18, chapter: 'Perfumes & Cosmetics' },
  { code: '3305', description: 'Preparations for use on the hair (shampoo, conditioner)', gstRate: 18, chapter: 'Personal Care' },
  { code: '3306', description: 'Preparations for oral/dental hygiene (toothpaste)', gstRate: 18, chapter: 'Personal Care' },
  { code: '3307', description: 'Pre-shave, shaving, after-shave, deodorants', gstRate: 18, chapter: 'Personal Care' },
  { code: '3401', description: 'Soap; organic surface-active products for washing', gstRate: 18, chapter: 'Soaps & Detergents' },
  { code: '3402', description: 'Organic surface-active agents; washing preparations', gstRate: 18, chapter: 'Soaps & Detergents' },
  { code: '3406', description: 'Candles, tapers, and the like', gstRate: 12, chapter: 'Misc Chemicals' },
  { code: '3605', description: 'Matches', gstRate: 12, chapter: 'Misc Chemicals' },
  { code: '3702', description: 'Photographic film in rolls, sensitised', gstRate: 18, chapter: 'Photographic' },
  { code: '3808', description: 'Insecticides, rodenticides, fungicides, herbicides', gstRate: 18, chapter: 'Agrochemicals' },
  { code: '3809', description: 'Finishing agents, dye carriers used in textile industry', gstRate: 18, chapter: 'Chemicals' },
  { code: '3816', description: 'Refractory cements, mortars, concretes and similar', gstRate: 18, chapter: 'Construction Chemicals' },
  { code: '3824', description: 'Prepared binders for foundry moulds; chemical products, misc.', gstRate: 18, chapter: 'Chemicals' },

  // ── Chapter 39–40: Plastics & Rubber ──
  { code: '3901', description: 'Polymers of ethylene, in primary forms', gstRate: 18, chapter: 'Plastics' },
  { code: '3902', description: 'Polymers of propylene or other olefins, in primary forms', gstRate: 18, chapter: 'Plastics' },
  { code: '3904', description: 'Polymers of vinyl chloride (PVC), in primary forms', gstRate: 18, chapter: 'Plastics' },
  { code: '3916', description: 'Monofilament, rods, sticks of plastics', gstRate: 18, chapter: 'Plastics' },
  { code: '3917', description: 'Tubes, pipes, hoses and fittings of plastics', gstRate: 18, chapter: 'Plastics' },
  { code: '3919', description: 'Self-adhesive plates, sheets, film, foil of plastics', gstRate: 18, chapter: 'Plastics' },
  { code: '3920', description: 'Other plates, sheets, film, foil, strip of plastics', gstRate: 18, chapter: 'Plastics' },
  { code: '3923', description: 'Plastic articles for conveying/packing goods (bags, sacks)', gstRate: 18, chapter: 'Plastics' },
  { code: '3924', description: 'Tableware, kitchenware, toilet articles of plastics', gstRate: 18, chapter: 'Plastics' },
  { code: '3926', description: 'Other articles of plastics (clips, rings, fittings)', gstRate: 18, chapter: 'Plastics' },
  { code: '4011', description: 'New pneumatic tyres of rubber (vehicles)', gstRate: 28, chapter: 'Rubber Products' },
  { code: '4016', description: 'Other articles of vulcanised rubber (hoses, seals)', gstRate: 18, chapter: 'Rubber Products' },

  // ── Chapter 44–49: Wood, Paper & Stationery ──
  { code: '4407', description: 'Wood sawn or chipped lengthwise, sliced or peeled', gstRate: 12, chapter: 'Wood & Timber' },
  { code: '4408', description: 'Sheets for veneering, plywood', gstRate: 12, chapter: 'Wood & Timber' },
  { code: '4410', description: 'Particle board, OSB of wood or other ligneous material', gstRate: 18, chapter: 'Wood & Timber' },
  { code: '4411', description: 'Fibreboard of wood (MDF, HDF)', gstRate: 18, chapter: 'Wood & Timber' },
  { code: '4412', description: 'Plywood, veneered panels and similar laminated wood', gstRate: 18, chapter: 'Wood & Timber' },
  { code: '4418', description: 'Builders joinery and carpentry of wood (doors, windows)', gstRate: 12, chapter: 'Wood Products' },
  { code: '4419', description: 'Tableware and kitchenware of wood', gstRate: 12, chapter: 'Wood Products' },
  { code: '4802', description: 'Uncoated paper and paperboard, for writing/printing', gstRate: 18, chapter: 'Paper' },
  { code: '4808', description: 'Corrugated paper and paperboard', gstRate: 18, chapter: 'Paper' },
  { code: '4811', description: 'Paper, paperboard, coated, impregnated (kraft paper)', gstRate: 18, chapter: 'Paper' },
  { code: '4818', description: 'Toilet paper, handkerchiefs, napkins of paper', gstRate: 18, chapter: 'Paper Products' },
  { code: '4819', description: 'Cartons, boxes, cases, bags of paper or paperboard', gstRate: 18, chapter: 'Packaging' },
  { code: '4820', description: 'Registers, account books, notebooks, diaries of paper', gstRate: 18, chapter: 'Stationery' },
  { code: '4821', description: 'Paper or paperboard labels of all kinds', gstRate: 18, chapter: 'Stationery' },
  { code: '4901', description: 'Printed books, brochures, leaflets (educational/reference)', gstRate: 0, chapter: 'Printed Matter' },
  { code: '4902', description: 'Newspapers, journals and periodicals', gstRate: 0, chapter: 'Printed Matter' },
  { code: '4909', description: 'Printed or illustrated postcards; greeting cards', gstRate: 12, chapter: 'Printed Matter' },

  // ── Chapter 50–63: Textiles & Apparel ──
  { code: '5201', description: 'Cotton, not carded or combed', gstRate: 0, chapter: 'Cotton' },
  { code: '5208', description: 'Woven fabrics of cotton (less than 85% cotton)', gstRate: 5, chapter: 'Woven Fabrics' },
  { code: '5210', description: 'Woven fabrics of cotton, less than 85%, bleached/dyed', gstRate: 5, chapter: 'Woven Fabrics' },
  { code: '5303', description: 'Jute and other textile bast fibres', gstRate: 0, chapter: 'Jute & Fibres' },
  { code: '5310', description: 'Woven fabrics of jute or other textile bast fibres', gstRate: 5, chapter: 'Jute & Fibres' },
  { code: '5401', description: 'Sewing thread of man-made filaments', gstRate: 12, chapter: 'Yarn & Thread' },
  { code: '5402', description: 'High tenacity yarn of nylon, polyester, etc.', gstRate: 12, chapter: 'Yarn & Thread' },
  { code: '5407', description: 'Woven fabrics of synthetic filament yarn', gstRate: 5, chapter: 'Woven Fabrics' },
  { code: '5513', description: 'Woven fabrics of synthetic staple fibres (below 85%)', gstRate: 5, chapter: 'Woven Fabrics' },
  { code: '5601', description: 'Wadding of textile materials and articles thereof', gstRate: 12, chapter: 'Textile Articles' },
  { code: '5806', description: 'Narrow woven fabrics; ribbons, labels, badges', gstRate: 12, chapter: 'Trimmings' },
  { code: '5901', description: 'Textile fabrics coated with gum/starch', gstRate: 12, chapter: 'Coated Fabrics' },
  { code: '6001', description: 'Pile fabrics, knitted or crocheted', gstRate: 5, chapter: 'Knitted Fabrics' },
  { code: '6101', description: "Men's or boys' overcoats, car-coats (knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6102', description: "Women's or girls' overcoats, car-coats (knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6103', description: "Men's suits, ensembles, jackets, trousers (knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6104', description: "Women's suits, ensembles, jackets, skirts (knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6105', description: "Men's shirts (knitted or crocheted)", gstRate: 12, chapter: 'Garments' },
  { code: '6106', description: "Women's blouses, shirts (knitted or crocheted)", gstRate: 12, chapter: 'Garments' },
  { code: '6107', description: "Men's underpants, briefs, nightshirts, pyjamas (knitted)", gstRate: 5, chapter: 'Garments' },
  { code: '6108', description: "Women's slips, petticoats, panties, nightdresses (knitted)", gstRate: 5, chapter: 'Garments' },
  { code: '6109', description: 'T-shirts, singlets, tank tops (knitted or crocheted)', gstRate: 12, chapter: 'Garments' },
  { code: '6110', description: 'Jerseys, pullovers, sweatshirts, waistcoats (knitted)', gstRate: 12, chapter: 'Garments' },
  { code: '6201', description: "Men's overcoats, anoraks, jackets (not knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6202', description: "Women's overcoats, anoraks, jackets (not knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6203', description: "Men's suits, ensembles, blazers, trousers (not knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6204', description: "Women's suits, ensembles, blazers, skirts (not knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6205', description: "Men's shirts (not knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6206', description: "Women's blouses, shirts (not knitted)", gstRate: 12, chapter: 'Garments' },
  { code: '6207', description: "Men's underpants, briefs, nightshirts, pyjamas (woven)", gstRate: 5, chapter: 'Garments' },
  { code: '6208', description: "Women's slips, petticoats, panties, nightdresses (woven)", gstRate: 5, chapter: 'Garments' },
  { code: '6209', description: 'Babies garments and clothing accessories', gstRate: 5, chapter: 'Garments' },
  { code: '6210', description: 'Garments made up of felt or nonwovens', gstRate: 12, chapter: 'Garments' },
  { code: '6211', description: 'Track suits, ski suits, swimwear', gstRate: 12, chapter: 'Garments' },
  { code: '6301', description: 'Blankets and travelling rugs', gstRate: 12, chapter: 'Home Textiles' },
  { code: '6302', description: 'Bed linen, table linen, toilet linen and kitchen linen', gstRate: 12, chapter: 'Home Textiles' },
  { code: '6303', description: 'Curtains (including drapes) and interior blinds', gstRate: 5, chapter: 'Home Textiles' },
  { code: '6304', description: 'Other furnishing articles (cushion covers, pillow cases)', gstRate: 5, chapter: 'Home Textiles' },
  { code: '6305', description: 'Sacks and bags of jute, cotton, man-made textile', gstRate: 12, chapter: 'Bags & Sacks' },
  { code: '6401', description: 'Waterproof footwear with outer soles and uppers of rubber', gstRate: 18, chapter: 'Footwear' },
  { code: '6403', description: 'Footwear with outer soles of rubber, plastics, leather', gstRate: 18, chapter: 'Footwear' },
  { code: '6404', description: 'Footwear with outer soles of rubber, plastics, textile uppers', gstRate: 18, chapter: 'Footwear' },

  // ── Chapter 68–70: Stone, Ceramics & Glass ──
  { code: '6801', description: 'Setts, curbstones and flagstones of natural stone', gstRate: 5, chapter: 'Stone Products' },
  { code: '6802', description: 'Worked monumental or building stone (tiles, slabs)', gstRate: 18, chapter: 'Stone Products' },
  { code: '6807', description: 'Articles of asphalt or of similar material', gstRate: 18, chapter: 'Building Materials' },
  { code: '6810', description: 'Articles of cement, concrete or artificial stone', gstRate: 18, chapter: 'Building Materials' },
  { code: '6901', description: 'Bricks, blocks, tiles of siliceous fossil meals', gstRate: 5, chapter: 'Ceramics' },
  { code: '6902', description: 'Refractory bricks, blocks, tiles (silicon carbide, magnesite)', gstRate: 18, chapter: 'Ceramics' },
  { code: '6904', description: 'Ceramic building bricks, flooring blocks, roofing tiles', gstRate: 5, chapter: 'Ceramics' },
  { code: '6907', description: 'Ceramic flags, paving, hearth or wall tiles (vitrified)', gstRate: 18, chapter: 'Ceramics' },
  { code: '6911', description: 'Tableware, kitchenware of porcelain or china', gstRate: 12, chapter: 'Ceramics' },
  { code: '6912', description: 'Ceramic tableware, kitchenware (other than porcelain)', gstRate: 18, chapter: 'Ceramics' },
  { code: '7003', description: 'Cast glass and rolled glass, in sheets or profiles', gstRate: 18, chapter: 'Glass' },
  { code: '7005', description: 'Float glass and surface ground/polished glass, in sheets', gstRate: 18, chapter: 'Glass' },
  { code: '7013', description: 'Glassware for table, kitchen, toilet (tumblers, bottles)', gstRate: 18, chapter: 'Glass Products' },

  // ── Chapter 71: Precious Metals & Jewellery ──
  { code: '7101', description: 'Pearls, natural or cultured, worked or unworked', gstRate: 0, chapter: 'Gems & Jewellery' },
  { code: '7102', description: 'Diamonds, worked or not (industrial or gem quality)', gstRate: 0, chapter: 'Gems & Jewellery' },
  { code: '7103', description: 'Precious stones other than diamonds', gstRate: 0, chapter: 'Gems & Jewellery' },
  { code: '7104', description: 'Synthetic or reconstructed precious or semi-precious stones', gstRate: 0, chapter: 'Gems & Jewellery' },
  { code: '7106', description: 'Silver (including silver plated with gold or platinum)', gstRate: 3, chapter: 'Precious Metals' },
  { code: '7108', description: 'Gold (including gold plated with platinum)', gstRate: 3, chapter: 'Precious Metals' },
  { code: '7113', description: 'Articles of jewellery and parts thereof of precious metal', gstRate: 3, chapter: 'Gems & Jewellery' },
  { code: '7114', description: "Goldsmiths' or silversmiths' wares of precious metal", gstRate: 3, chapter: 'Gems & Jewellery' },
  { code: '7116', description: 'Articles of natural/cultured pearls, precious stones', gstRate: 3, chapter: 'Gems & Jewellery' },

  // ── Chapter 72–73: Iron & Steel ──
  { code: '7201', description: 'Pig iron and spiegeleisen in pigs, blocks or other', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7204', description: 'Ferrous waste and scrap; remelting scrap ingots', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7205', description: 'Granules and powders of pig iron, spiegeleisen', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7206', description: 'Iron and non-alloy steel in ingots or other primary forms', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7207', description: 'Semi-finished products of iron or non-alloy steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7208', description: 'Flat-rolled products of iron or non-alloy steel, hot-rolled', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7209', description: 'Flat-rolled products of iron or non-alloy steel, cold-rolled', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7210', description: 'Flat-rolled products of iron coated (zinc/tin/chrome)', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7213', description: 'Bars and rods, hot-rolled, in irregularly wound coils', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7214', description: 'Other bars and rods of iron or non-alloy steel (TMT bars)', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7215', description: 'Other bars and rods of iron or non-alloy steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7216', description: 'Angles, shapes and sections of iron or non-alloy steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7217', description: 'Wire of iron or non-alloy steel (binding wire, GI wire)', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7219', description: 'Flat-rolled products of stainless steel', gstRate: 18, chapter: 'Stainless Steel' },
  { code: '7220', description: 'Flat-rolled products of stainless steel, cold-reduced', gstRate: 18, chapter: 'Stainless Steel' },
  { code: '7222', description: 'Other bars and rods of stainless steel', gstRate: 18, chapter: 'Stainless Steel' },
  { code: '7225', description: 'Flat-rolled products of other alloy steel, hot-rolled', gstRate: 18, chapter: 'Alloy Steel' },
  { code: '7228', description: 'Other bars and rods of other alloy steel', gstRate: 18, chapter: 'Alloy Steel' },
  { code: '7301', description: 'Sheet piling and welded angles/shapes of iron or steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7302', description: 'Railway or tramway track construction material (rails)', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7303', description: 'Tubes, pipes and hollow profiles, of cast iron', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7304', description: 'Tubes, pipes and hollow profiles, seamless, of iron/steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7305', description: 'Other tubes and pipes, welded, of iron or steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7306', description: 'Other tubes, pipes and hollow profiles of iron or steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7307', description: 'Tube or pipe fittings of iron or steel (elbows, couplings)', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7308', description: 'Structures and parts of iron or steel (bridges, columns)', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7312', description: 'Stranded wire, ropes, cables of iron or steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7313', description: 'Barbed wire of iron or steel; fencing wire', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7315', description: 'Chain and parts thereof, of iron or steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7317', description: 'Nails, tacks, drawing pins, staples of iron or steel', gstRate: 18, chapter: 'Fasteners' },
  { code: '7318', description: 'Screws, bolts, nuts, washers of iron or steel', gstRate: 18, chapter: 'Fasteners' },
  { code: '7320', description: 'Springs and leaves for springs of iron or steel', gstRate: 18, chapter: 'Iron & Steel' },
  { code: '7323', description: 'Table, kitchen, household articles of iron or steel', gstRate: 18, chapter: 'Household Metal' },
  { code: '7326', description: 'Other articles of iron or steel (chain links, hooks)', gstRate: 18, chapter: 'Iron & Steel' },

  // ── Chapter 74–76: Copper & Aluminium ──
  { code: '7401', description: 'Copper mattes; cement copper', gstRate: 18, chapter: 'Copper' },
  { code: '7403', description: 'Refined copper and copper alloys, unwrought', gstRate: 18, chapter: 'Copper' },
  { code: '7408', description: 'Copper wire', gstRate: 18, chapter: 'Copper' },
  { code: '7409', description: 'Copper plates, sheets, strip', gstRate: 18, chapter: 'Copper' },
  { code: '7411', description: 'Copper tubes and pipes', gstRate: 18, chapter: 'Copper' },
  { code: '7601', description: 'Unwrought aluminium', gstRate: 18, chapter: 'Aluminium' },
  { code: '7604', description: 'Aluminium bars, rods, profiles', gstRate: 18, chapter: 'Aluminium' },
  { code: '7606', description: 'Aluminium plates, sheets, strip', gstRate: 18, chapter: 'Aluminium' },
  { code: '7608', description: 'Aluminium tubes and pipes', gstRate: 18, chapter: 'Aluminium' },
  { code: '7610', description: 'Aluminium structures and parts (doors, windows, railings)', gstRate: 18, chapter: 'Aluminium' },
  { code: '7612', description: 'Casks, drums, cans, boxes of aluminium', gstRate: 18, chapter: 'Aluminium' },
  { code: '7616', description: 'Other articles of aluminium (foil, fittings)', gstRate: 18, chapter: 'Aluminium' },

  // ── Chapter 82–83: Tools, Hardware ──
  { code: '8201', description: 'Hand tools (spades, shovels, picks, hoes, rakes)', gstRate: 18, chapter: 'Tools' },
  { code: '8203', description: 'Files, rasps, pliers, wire cutters, spanners', gstRate: 18, chapter: 'Tools' },
  { code: '8204', description: 'Hand-operated spanners and wrenches, socket wrenches', gstRate: 18, chapter: 'Tools' },
  { code: '8205', description: 'Hand tools not elsewhere specified (hammers, chisels, drills)', gstRate: 18, chapter: 'Tools' },
  { code: '8207', description: 'Interchangeable tools for hand/machine tools (drill bits)', gstRate: 18, chapter: 'Tools' },
  { code: '8208', description: 'Knives and cutting blades for machines', gstRate: 18, chapter: 'Tools' },
  { code: '8301', description: 'Padlocks, locks, clasps of base metal', gstRate: 18, chapter: 'Locks & Hardware' },
  { code: '8302', description: 'Base metal mountings, fittings for doors, windows, furniture', gstRate: 18, chapter: 'Hardware' },
  { code: '8310', description: 'Sign-plates, name-plates, number plates of base metal', gstRate: 18, chapter: 'Hardware' },

  // ── Chapter 84: Industrial Machinery ──
  { code: '8401', description: 'Nuclear reactors; fuel elements for nuclear reactors', gstRate: 18, chapter: 'Machinery' },
  { code: '8406', description: 'Steam turbines and other vapour turbines', gstRate: 18, chapter: 'Machinery' },
  { code: '8407', description: 'Spark-ignition reciprocating/rotary internal combustion engines', gstRate: 28, chapter: 'Engines' },
  { code: '8408', description: 'Compression-ignition internal combustion piston engines (diesel)', gstRate: 28, chapter: 'Engines' },
  { code: '8411', description: 'Turbo-jets, turbo-propellers and other gas turbines', gstRate: 18, chapter: 'Engines' },
  { code: '8413', description: 'Pumps for liquids; liquid elevators', gstRate: 18, chapter: 'Pumps & Compressors' },
  { code: '8414', description: 'Air/vacuum pumps, air/gas compressors, fans', gstRate: 18, chapter: 'Pumps & Compressors' },
  { code: '8415', description: 'Air conditioning machines (split AC, window AC)', gstRate: 28, chapter: 'HVAC' },
  { code: '8416', description: 'Furnace burners for liquid/gaseous fuel', gstRate: 18, chapter: 'Heating' },
  { code: '8417', description: 'Industrial or laboratory furnaces and ovens (non-electric)', gstRate: 18, chapter: 'Heating' },
  { code: '8418', description: 'Refrigerators, freezers and other refrigerating equipment', gstRate: 28, chapter: 'Refrigeration' },
  { code: '8419', description: 'Machinery for treating material by heating/cooling', gstRate: 18, chapter: 'Machinery' },
  { code: '8421', description: 'Centrifuges; filtering/purifying machinery for liquids/gas', gstRate: 18, chapter: 'Machinery' },
  { code: '8422', description: 'Dishwashing machines; packaging/bottling/sealing machinery', gstRate: 28, chapter: 'Machinery' },
  { code: '8423', description: 'Weighing machinery (including weighbridges)', gstRate: 18, chapter: 'Weighing' },
  { code: '8428', description: 'Lifting, handling, loading/unloading machinery (conveyor)', gstRate: 18, chapter: 'Material Handling' },
  { code: '8429', description: 'Self-propelled bulldozers, graders, excavators (JCB)', gstRate: 28, chapter: 'Construction Machinery' },
  { code: '8443', description: 'Printing machinery; machines for ancillary use (photocopier)', gstRate: 18, chapter: 'Printing' },
  { code: '8450', description: 'Household or laundry-type washing machines', gstRate: 28, chapter: 'Appliances' },
  { code: '8451', description: 'Industrial washing/dry-cleaning/drying machines', gstRate: 18, chapter: 'Laundry' },
  { code: '8452', description: 'Sewing machines', gstRate: 12, chapter: 'Sewing' },
  { code: '8467', description: 'Tools for working in the hand, pneumatic or motor-driven', gstRate: 18, chapter: 'Power Tools' },
  { code: '8471', description: 'Automatic data processing machines (computers, laptops)', gstRate: 18, chapter: 'Computers & IT' },
  { code: '8473', description: 'Parts and accessories of computers and peripherals', gstRate: 18, chapter: 'Computers & IT' },
  { code: '8481', description: 'Taps, cocks, valves and similar appliances for pipes', gstRate: 18, chapter: 'Valves & Fittings' },
  { code: '8482', description: 'Ball bearings, roller bearings, needle roller bearings', gstRate: 18, chapter: 'Bearings' },
  { code: '8483', description: 'Transmission shafts, cranks, gear boxes, clutches, flywheels', gstRate: 18, chapter: 'Transmission' },
  { code: '8484', description: 'Gaskets and similar joints of metal sheeting', gstRate: 18, chapter: 'Gaskets' },
  { code: '8486', description: 'Machines and apparatus for semiconductor manufacture', gstRate: 0, chapter: 'Electronics Manufacturing' },

  // ── Chapter 85: Electrical Equipment & Electronics ──
  { code: '8501', description: 'Electric motors and generators', gstRate: 18, chapter: 'Electrical' },
  { code: '8502', description: 'Electric generating sets and rotary converters', gstRate: 18, chapter: 'Electrical' },
  { code: '8504', description: 'Electrical transformers, static converters, inductors, UPS', gstRate: 18, chapter: 'Electrical' },
  { code: '8505', description: 'Permanent magnets; electromagnets', gstRate: 18, chapter: 'Electrical' },
  { code: '8506', description: 'Primary cells and primary batteries (AA, AAA, etc.)', gstRate: 28, chapter: 'Batteries' },
  { code: '8507', description: 'Electric accumulators (lead-acid, Li-ion batteries)', gstRate: 28, chapter: 'Batteries' },
  { code: '8509', description: 'Electromechanical domestic appliances (mixers, grinders)', gstRate: 28, chapter: 'Appliances' },
  { code: '8510', description: 'Electric shavers, hair clippers and hair-removing appliances', gstRate: 28, chapter: 'Appliances' },
  { code: '8513', description: 'Portable electric lamps (torches, lanterns)', gstRate: 18, chapter: 'Lighting' },
  { code: '8516', description: 'Electric water heaters, hair dryers, geysers, irons', gstRate: 28, chapter: 'Appliances' },
  { code: '8517', description: 'Telephone sets including smartphones and other devices', gstRate: 18, chapter: 'Telecom Devices' },
  { code: '8518', description: 'Microphones, loudspeakers, headphones, audio amplifiers', gstRate: 18, chapter: 'Audio' },
  { code: '8519', description: 'Sound recording/reproducing apparatus (MP3 players)', gstRate: 28, chapter: 'Audio' },
  { code: '8523', description: 'Discs, tapes, solid-state storage devices for sound/video', gstRate: 18, chapter: 'Storage Media' },
  { code: '8525', description: 'Transmission apparatus for radio/TV broadcasting', gstRate: 18, chapter: 'Broadcasting' },
  { code: '8526', description: 'Radar apparatus, radio navigational aid apparatus, GPS', gstRate: 18, chapter: 'Navigation' },
  { code: '8528', description: 'Monitors, projectors, TVs (receiving apparatus for television)', gstRate: 28, chapter: 'Displays & TV' },
  { code: '8531', description: 'Electric sound/visual signalling apparatus (alarms, bells)', gstRate: 18, chapter: 'Signalling' },
  { code: '8532', description: 'Electrical capacitors (fixed, variable)', gstRate: 18, chapter: 'Electronic Components' },
  { code: '8533', description: 'Electrical resistors (fixed, variable)', gstRate: 18, chapter: 'Electronic Components' },
  { code: '8534', description: 'Printed circuits (PCBs)', gstRate: 18, chapter: 'Electronic Components' },
  { code: '8536', description: 'Electrical apparatus for switching circuits (switches, sockets, relays)', gstRate: 18, chapter: 'Electrical' },
  { code: '8537', description: 'Boards, panels, consoles for electrical control (switchgear)', gstRate: 18, chapter: 'Switchgear' },
  { code: '8538', description: 'Parts for apparatus of 8535, 8536, 8537', gstRate: 18, chapter: 'Electrical' },
  { code: '8539', description: 'Electric filament/discharge lamps, LED lamps', gstRate: 12, chapter: 'Lighting' },
  { code: '8540', description: 'Thermionic, cold cathode or photo-cathode tubes', gstRate: 18, chapter: 'Electronic Components' },
  { code: '8541', description: 'Semiconductor devices, diodes, transistors, LEDs, solar cells', gstRate: 18, chapter: 'Semiconductors' },
  { code: '8542', description: 'Electronic integrated circuits (microchips, processors)', gstRate: 18, chapter: 'Semiconductors' },
  { code: '8544', description: 'Insulated wire, cable, coaxial cable, optical fibre cable', gstRate: 18, chapter: 'Cables & Wires' },
  { code: '8545', description: 'Carbon electrodes, carbon brushes, arc-lamp carbons', gstRate: 18, chapter: 'Electrical' },
  { code: '8546', description: 'Electrical insulators of any material (porcelain, glass)', gstRate: 18, chapter: 'Electrical' },
  { code: '8547', description: 'Insulating fittings for electrical machines (junction boxes)', gstRate: 18, chapter: 'Electrical' },

  // ── Chapter 87: Motor Vehicles & Parts ──
  { code: '8701', description: 'Tractors', gstRate: 12, chapter: 'Vehicles' },
  { code: '8702', description: 'Motor vehicles for the transport of ten or more persons (bus)', gstRate: 28, chapter: 'Vehicles' },
  { code: '8703', description: 'Motor cars and other motor vehicles (passenger cars)', gstRate: 28, chapter: 'Vehicles' },
  { code: '8704', description: 'Motor vehicles for the transport of goods (trucks)', gstRate: 28, chapter: 'Vehicles' },
  { code: '8706', description: 'Chassis fitted with engines for motor vehicles', gstRate: 28, chapter: 'Vehicles' },
  { code: '8707', description: 'Bodies (including cabs) for motor vehicles', gstRate: 28, chapter: 'Vehicles' },
  { code: '8708', description: 'Parts and accessories of motor vehicles (brakes, clutches)', gstRate: 28, chapter: 'Auto Parts' },
  { code: '8711', description: 'Motorcycles, scooters, mopeds, and cycles with auxiliary motor', gstRate: 28, chapter: 'Two Wheelers' },
  { code: '8712', description: 'Bicycles and other cycles, not motorised', gstRate: 12, chapter: 'Cycles' },
  { code: '8714', description: 'Parts and accessories for vehicles (tyres, saddles)', gstRate: 18, chapter: 'Cycle Parts' },
  { code: '8716', description: 'Trailers and semi-trailers; other vehicles, not self-propelled', gstRate: 28, chapter: 'Trailers' },

  // ── Chapter 90: Instruments & Medical Equipment ──
  { code: '9004', description: 'Spectacles, goggles and the like (corrective, protective)', gstRate: 12, chapter: 'Optics' },
  { code: '9006', description: 'Photographic cameras (not cinematographic)', gstRate: 18, chapter: 'Cameras' },
  { code: '9007', description: 'Cinematographic cameras and projectors', gstRate: 18, chapter: 'Cameras' },
  { code: '9013', description: 'Liquid crystal devices; lasers (not laser diodes)', gstRate: 18, chapter: 'Optics' },
  { code: '9018', description: 'Instruments and appliances used in medical/surgical sciences', gstRate: 12, chapter: 'Medical Devices' },
  { code: '9019', description: 'Mechano-therapy/massage appliances; artificial respiration apparatus', gstRate: 12, chapter: 'Medical Devices' },
  { code: '9020', description: 'Other breathing appliances and gas masks', gstRate: 12, chapter: 'Medical Devices' },
  { code: '9021', description: 'Orthopaedic appliances, surgical belts, trusses; artificial parts', gstRate: 5, chapter: 'Medical Devices' },
  { code: '9022', description: 'X-ray apparatus; alpha, beta, gamma radiation apparatus', gstRate: 12, chapter: 'Medical Devices' },
  { code: '9025', description: 'Hydrometers, thermometers, barometers, hygrometers', gstRate: 18, chapter: 'Instruments' },
  { code: '9026', description: 'Instruments for measuring flow, level, pressure of liquids/gas', gstRate: 18, chapter: 'Instruments' },
  { code: '9027', description: 'Instruments and apparatus for physical/chemical analysis', gstRate: 18, chapter: 'Lab Equipment' },
  { code: '9030', description: 'Oscilloscopes, spectrum analysers, signal generators', gstRate: 18, chapter: 'Test Equipment' },
  { code: '9032', description: 'Automatic regulating or controlling instruments', gstRate: 18, chapter: 'Instruments' },

  // ── Chapter 94: Furniture ──
  { code: '9401', description: 'Seats (chairs, sofas, benches) with or without metal frames', gstRate: 18, chapter: 'Furniture' },
  { code: '9402', description: 'Medical, surgical, dental or veterinary furniture', gstRate: 12, chapter: 'Medical Furniture' },
  { code: '9403', description: 'Other furniture (desks, tables, cupboards, wardrobes)', gstRate: 18, chapter: 'Furniture' },
  { code: '9404', description: 'Mattress supports; mattresses, quilts, feather-beds', gstRate: 12, chapter: 'Mattresses' },
  { code: '9405', description: 'Lamps, lighting fittings, illuminated signs, chandeliers', gstRate: 12, chapter: 'Lighting' },
  { code: '9406', description: 'Prefabricated buildings (portable, modular)', gstRate: 18, chapter: 'Construction' },

  // ── Chapter 95–96: Toys, Sports & Misc ──
  { code: '9503', description: 'Tricycles, scooters, pedal cars; toys; reduced-scale models', gstRate: 12, chapter: 'Toys & Games' },
  { code: '9504', description: 'Video games, arcade games, playing cards, chess sets', gstRate: 18, chapter: 'Games' },
  { code: '9506', description: 'Articles for sports, gymnastics, athletics, swimming', gstRate: 18, chapter: 'Sports Equipment' },
  { code: '9603', description: 'Brooms, brushes, mops, feather dusters', gstRate: 18, chapter: 'Cleaning' },
  { code: '9613', description: 'Cigarette lighters and other lighters (gas lighters)', gstRate: 28, chapter: 'Misc' },
  { code: '9615', description: 'Combs, hair-slides and the like; hair-pins', gstRate: 18, chapter: 'Personal Accessories' },

  // ── SAC (Service Accounting Codes) ──
  { code: '9954', description: 'Construction services (building, civil, road, bridge, dam)', gstRate: 18, chapter: 'Construction Services' },
  { code: '995411', description: 'Construction of buildings (residential/commercial — new)', gstRate: 18, chapter: 'Construction Services' },
  { code: '995412', description: 'Construction of other non-residential buildings', gstRate: 18, chapter: 'Construction Services' },
  { code: '995413', description: 'Construction of civil engineering works', gstRate: 18, chapter: 'Construction Services' },
  { code: '995415', description: 'Interior decoration / painting / flooring services', gstRate: 18, chapter: 'Construction Services' },
  { code: '9961', description: 'Services in wholesale trade (commission agents, auctioneers)', gstRate: 18, chapter: 'Trade Services' },
  { code: '9962', description: 'Services in retail trade (commission agents)', gstRate: 18, chapter: 'Trade Services' },
  { code: '9963', description: 'Accommodation, food and beverage services (hotels, restaurants)', gstRate: 18, chapter: 'Hospitality' },
  { code: '9964', description: 'Passenger transport services (taxi, bus, flight)', gstRate: 5, chapter: 'Transport' },
  { code: '9965', description: 'Goods transport services (road, rail, air, sea)', gstRate: 5, chapter: 'Transport' },
  { code: '9966', description: 'Rental/leasing services of transport vehicles', gstRate: 18, chapter: 'Transport' },
  { code: '9967', description: 'Supporting services in transport (loading, packing, freight brokerage)', gstRate: 18, chapter: 'Transport' },
  { code: '9968', description: 'Postal and courier services', gstRate: 18, chapter: 'Logistics' },
  { code: '9969', description: 'Electricity, gas, water and other distribution services', gstRate: 18, chapter: 'Utilities' },
  { code: '9971', description: 'Financial and related services (banking, lending, investment)', gstRate: 18, chapter: 'Financial Services' },
  { code: '9972', description: 'Real estate services (buying, selling, renting property)', gstRate: 18, chapter: 'Real Estate' },
  { code: '9973', description: 'Leasing/rental services of goods without operator', gstRate: 18, chapter: 'Leasing' },
  { code: '9974', description: 'Telecommunications and broadcasting services', gstRate: 18, chapter: 'Telecom Services' },
  { code: '9975', description: 'Electricity, gas, water and other distribution services', gstRate: 18, chapter: 'Utilities' },
  { code: '9981', description: 'Information technology and computer services (software, IT support)', gstRate: 18, chapter: 'IT Services' },
  { code: '9982', description: 'Legal and accounting/audit services', gstRate: 18, chapter: 'Professional Services' },
  { code: '9983', description: 'Management consulting and business advisory services', gstRate: 18, chapter: 'Professional Services' },
  { code: '9984', description: 'Scientific research and development services', gstRate: 18, chapter: 'R&D Services' },
  { code: '9985', description: 'Support services (facilities management, cleaning, security)', gstRate: 18, chapter: 'Business Support' },
  { code: '9986', description: 'Support services to agriculture, hunting, forestry and fishing', gstRate: 0, chapter: 'Agriculture Services' },
  { code: '9987', description: 'Maintenance, repair and installation services', gstRate: 18, chapter: 'Repair Services' },
  { code: '9988', description: 'Manufacturing services on physical inputs (job work)', gstRate: 18, chapter: 'Job Work' },
  { code: '9989', description: 'Other manufacturing services (food processing, distilling)', gstRate: 18, chapter: 'Manufacturing Services' },
  { code: '9991', description: 'Public administration and other government services', gstRate: 0, chapter: 'Government Services' },
  { code: '9992', description: 'Education services (schools, colleges, coaching)', gstRate: 0, chapter: 'Education' },
  { code: '9993', description: 'Human health and social care services (hospitals, clinics)', gstRate: 0, chapter: 'Health Services' },
  { code: '9994', description: 'Sewage and waste collection, treatment and disposal', gstRate: 5, chapter: 'Waste Management' },
  { code: '9995', description: 'Services of membership organisations (clubs, associations)', gstRate: 18, chapter: 'Membership Services' },
  { code: '9996', description: 'Recreational, cultural and sporting services (cinema, events)', gstRate: 18, chapter: 'Entertainment' },
  { code: '9997', description: 'Other services (tailoring, beauty salons, repair shops)', gstRate: 18, chapter: 'Other Services' },
  { code: '9998', description: 'Domestic services (household workers, domestic help)', gstRate: 0, chapter: 'Domestic Services' },
];

export function searchHSN(query: string, limit = 20): HSNEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return HSN_DATA.slice(0, limit);

  const byCode = HSN_DATA.filter(e => e.code.startsWith(q));
  const byDesc = HSN_DATA.filter(
    e => !e.code.startsWith(q) && e.description.toLowerCase().includes(q)
  );

  return [...byCode, ...byDesc].slice(0, limit);
}

export function getHSNByCode(code: string): HSNEntry | undefined {
  return HSN_DATA.find(e => e.code === code);
}
